### ISSUE TITLE
Veteran coworkers should have admin access to the Slack workspace

### ISSUE THREAD

**Issue by pmotch** [cowork-evansville/feedback#1]
Right now only Gage has admin access to the Slack workspace. A few issues with that:
* It's a bottleneck
* It's unnecessarily restrictive
* Holds back creative ideas you can do with Slack that only admins can enable (the barrier to work with fewer admins stifles the will to want to do these creative things)

Solution: give admin access to a few trusted coworkers. Ideally ones who've been here for a while. I nominate Sam, Amy, or Edgar.

**Comment by alliebusch** [comment]
Taken care of! Andrea granted access to Sam, Amy, and Edgar.

**Comment by pmotch** [comment]
Thanks @alliebusch! Closing the issue!
